name: randomHearts
author: Jodabeats
api-version: 1.13
description: This plugin assigns each player with a different, random amount of hearts every 24 hours
commands:
  heart:
    description: random hearts command
    usage: "/hearts [on/off]"
version: 1.0
main: me.joda.hearts.Main
